language: python
python:
  - "3.6.7"
install:
  - pip3 install homeassistant
script:
  - hass -c . --script check_config --info all
before_install:
  - mkdir android
  - mv ci_tests/travis_adbkey android/adbkey
  - mv ci_tests/travis_adbkey.pub android/adbkey.pub
  - mv ci_tests/travis_fire_tv.yaml components/media_player/dalebedroom_firetv.yaml
  - mv ci_tests/travis_secrets.yaml secrets.yaml