homeassistant:

  name: Home

  latitude: !secret zone_home_latitude
  longitude: !secret zone_home_longitude
  elevation: !secret elevation

  # metric for Metric, imperial for Imperial
  unit_system: metric

  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone

  # Load packages
  packages: !include_dir_named components/packages

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  #base_url: homeassistant.lab.local:8123
  base_url: !secret homeassistant_url