homeassistant:

  name: Home

  latitude: !secret zone_home_latitude
  longitude: !secret zone_home_longitude
  elevation: !secret elevation

  # metric for Metric, imperial for Imperial
  unit_system: metric

  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone

  # Load packages
  packages: !include_dir_named components/packages

  # Load customisations
  customize: !include customize.yaml

# https://github.com/home-assistant/home-assistant/issues/21307
# People
person:
  - name: Dale
    id: !secret hass_user_id_dale
    user_id: !secret hass_user_id_dale
    device_trackers:
      - device_tracker.phone_dale_personal_ariela

  - name: Cait
    id: !secret hass_user_id_cait