  version: '3'
  services:
    homeassistant:
      container_name: homeassistant
      image: homeassistant/home-assistant
      volumes:
        - /srv/homeassistant:/config
        - /etc/localtime:/etc/localtime:ro
      restart: always
      ports:
        - 8123:8123