  version: '3'
  services:
    homeassistant:
      container_name: home-assistant2
      image: homeassistant/home-assistant
      volumes:
        - /srv/homeassistant2:/config
        - /etc/localtime:/etc/localtime:ro
      restart: always
      ports:
        - 8123:8123