  version: '3'
  services:
    homeassistant:
      container_name: home-assistant2
      image: homeassistant/home-assistant
      volumes:
        - /srv/homeassistant:/config
        - /etc/localtime:/etc/localtime:ro
      restart: always
      network_mode: host