# https://www.home-assistant.io/lovelace

title: Home Control Panel
resources:
  - url: /lovelace/custom_cards/weather_card/weather-card.js
    type: module
views:
  - !include lovelace/views/dashboard.yaml
  - !include lovelace/views/weather.yaml