# https://www.home-assistant.io/lovelace

title: Home Control Panel
resources:
  - url: /config/lovelace/custom_cards/weather_card/weather-card.js
    type: module
views:
  - !include /config/lovelace/views/dashboard.yaml
  - !include /config/lovelace/views/weather.yaml