# https://www.home-assistant.io/lovelace

title: HomeAssistant
resources:
  - url: /customcards/lovelace/custom-cards/compact-custom-header-card/compact-custom-header.js?track=true
    type: module
  - url: /customcards/lovelace/custom-cards/weather-card/weather-card.js?track=true
    type: module
views:
  - !include lovelace/views/mobile_view_home.yaml
  - !include lovelace/views/mobile_view_weather.yaml