# https://www.home-assistant.io/lovelace

title: HomeAssistant
resources:
  - url: /local/lovelace/custom_cards/weather_card/weather-card.js?v=0.000001
    type: module
views:
  - !include lovelace/views/dashboard.yaml
  - !include lovelace/views/weather.yaml