# https://www.home-assistant.io/docs/authentication/providers

homeassistant:
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 127.0.0.1
        - 192.168.1.0/24