# https://www.home-assistant.io/components/automation/

- alias: disable_pi_hole
  trigger:
    platform: state
    entity_id: input_select.pihole_time
  action:
    service: shell_command.pihole_disable