# https://www.home-assistant.io/components/sensor.template/

- platform: template
  sensors:
    battery_phone_dale_personal:
      friendly_name: Dale's Personal Phone Battery
      unit_of_measurement: '%'
      value_template: >-
          {%- if states.device_tracker.phone_dale_personal_ariela.attributes.battery %}
              {{ states.device_tracker.phone_dale_personal_ariela.attributes.battery|round }}
          {% else %}
              {{ states.sensor.battery_phone_dale_personal.state }}
          {%- endif %}
      device_class: battery

- platform: template
  sensors:
    battery_phone_dale_work:
      friendly_name: Dale's Work Phone Battery
      unit_of_measurement: '%'
      value_template: >-
          {%- if states.device_tracker.phone_dale_work_ariela.attributes.battery %}
              {{ states.device_tracker.phone_dale_work_ariela.attributes.battery|round }}
          {% else %}
              {{ states.sensor.battery_phone_dale_work.state }}
          {%- endif %}
      device_class: battery

- platform: template
  sensors:
    battery_tablet_dale_10:
      friendly_name: Dale's 10" Tablet Battery
      unit_of_measurement: '%'
      value_template: >-
          {%- if states.device_tracker.tablet_dale_ariela.attributes.battery %}
              {{ states.device_tracker.tablet_dale_ariela.attributes.battery|round }}
          {% else %}
              {{ states.sensor.battery_tablet_dale_10.state }}
          {%- endif %}
      device_class: battery