# https://www.home-assistant.io/components/sensor.pi_hole/

- platform: pi_hole
  host: 192.168.1.100
  monitored_conditions:
    - ads_blocked_today
    - ads_percentage_today
    - dns_queries_today
    - domains_being_blocked
    - queries_cached
    - queries_forwarded
    - unique_clients
    - unique_domains

- platform: command_line
  name: pihole_status
  command: curl -X GET 'http://pihole.lab.local/admin/api.php?status&auth='
  value_template: >
    {{ value_json.status }}